model_type: baselines

model_List :
  - GMM
magnet_det:
  - MagNet_L1
  - MagNet_JSD 
artifacts:
  - Artifacts
manda:
  - Manda
# magnet:
#   - MagSec

n_components : 1
n_neighbors : 1
num_jobs : 8
random_state : 1 
contamination : 0.0001
