from .get_conv_net import *
from .train_conv_net import *
from .test_conv_net import *

from .collections.simple_mnist import *
from .collections.simple_speech import *
from .collections.simple_mnist_magnet import *
from .collections.simple_fashion import *
from .collections.simple_cifar10_v1 import *
from .collections.simple_cifar10_v2 import *
from .collections.simple_cifar10 import *
from .collections.simple_cancer import *
from .collections.simple_gtsrb import *
from .collections.resnet_cifar10 import *
from .collections.badnet import *
from .collections.resnet_transfer import *
from .collections.cnn_classifier_3x32x32 import *
from .collections.cnn_classifier_1x64x81 import *
from .collections.cnn_classifier_1x64x64 import *
from .collections.cnn_classifier_3x150x150 import *
from .collections.resnet_models import *
from .collections.cnn_radioml import *
from .collections.cnn_classifier_1x500x90 import *
