# Dataset params
name : mnist
num_classes : 10
num_feats : 128 
num_channels : 1
width : 28
height : 28

# Classifier params
batch_size : 64
epochs : 2
loss_fn : cross
optim : adam
lr : 0.001

# Autoencoder params
lr_ae : 0.001
ae_epochs : 10
ae_hidden_layers : 3
ae_latent_dim : 256
noise_factor : 0.50
sparse_factor : 0.1

# Backdoor params
trigger_label : 0
poison_ratio : 0.1

# Evaluation parameter
eps:
- 0.30 
max_fpr : 0.01

#artifacts
bandwidth : 1.2

classes : ['0', '1', '2', '3',
           '4', '5', '6', '7', '8', '9']


atk_cfg:
  RN:
    eps: 0.30
  FGSM:
    eps: 0.30
  BIM:
    eps: 0.30
    alpha: 0.01
    steps: 25
  PGD:
    eps: 0.30
    alpha: 0.01
    steps: 25
  JSMA:
    theta: 0.50
    gamma: 0.20
  UAP:
    eps: 0.30
    delta: 0.50
    max_iter: 250
    attacker: fgsm
  C&W:
    c: 1.0
    confidence: 19.0
    max_iter: 10
    binary_search_step: 50
    learning_rate: 0.025
  BadNet:
    trigger_label: 2
    poison_ratio: 0.1
  Square:
    eps: 0.30